# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InvasivesBC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InvasivesBC
  pod 'IQKeyboardManagerSwift'
  pod 'ReachabilitySwift'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Extended'

  target 'InvasivesBCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InvasivesBCUITests' do
    # Pods for testing
  end

end
